# Generated by Django 4.2.7 on 2025-11-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='external_metadata',
            field=models.JSONField(blank=True, help_text='Метаданные из Proxy Service', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='proxy_document_id',
            field=models.CharField(blank=True, help_text='ID документа в Proxy Service', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='external_order_data',
            field=models.JSONField(blank=True, help_text='Данные заказа из Proxy Service', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='proxy_order_id',
            field=models.CharField(blank=True, help_text='ID заказа в Proxy Service', max_length=100, null=True),
        ),
    ]
