# Generated by Django 4.2.7 on 2025-11-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_external_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='unit_type',
            field=models.CharField(choices=[('page', 'Page'), ('document', 'Document'), ('mb', 'Megabyte'), ('hour', 'Hour')], default='page', max_length=20),
        ),
    ]
